### ISSUE TITLE
Support game pads

### ISSUE THREAD

**Issue by willwade** [AceCentre/Echo#29]
Gamepads are now super well supported on iOS 17 as an input device. It would make a nice interface technique if it supported them well eg the arrow keys.

**Comment by gavinhenderson** [comment]
In theory they should already work as external switches in Echo

**Comment by gavinhenderson** [comment]
@willwade do you mind testing this again now that I have rewritten the keyboard controlls. It uses raw HID now so should work with Game Pads.

Rewrite comes in version v1.2.0

**Comment by gavinhenderson** [comment]
Note: 1.2.0 did NOT fix this issue

**Comment by gavinhenderson** [comment]
Note: https://developer.apple.com/documentation/gamecontroller/gccontroller
