### ISSUE TITLE
Investigate possible ways to split audio sources across two devices

### ISSUE THREAD

**Issue by gavinhenderson** [AceCentre/Echo#37]
Note, this is not to do the work but instead to figure out the best way to do it then create the tasks to do it. Those tasks will then be prioritised seperately

**Comment by willwade** [comment]
Maybe of interest https://developer.apple.com/forums/thread/5787

**Comment by gavinhenderson** [comment]
Possible solution: 

https://www.amazon.co.uk/dp/B00CS8FQJC?ref_=cm_sw_r_apin_dp_63MCRWQDQ4D8PQKGAPM3&language=en-GB
https://www.1mii.com/product-item/ml100/

**Comment by willwade** [comment]
If we were to develop an electronics board it would be worth googling esp32-s3 (needs multicore), A2DP, [see this library](https://github.com/pschatzmann/ESP32-A2DP), and the VS1053

Interesting board: https://kateiren.github.io/esp32-webradio/ 
https://github.com/paulgreg/esp32-bluetooth-audio-adafruit/ and hackaday page:
https://hackaday.io/project/183183-esp32-bluetooth-audio-receiver

Note what we would also need is:
- Headphone jack (note some of those VS1053 development boards have that)
