### ISSUE TITLE
Single letters read incorrectly

### ISSUE THREAD

**Issue by gavinhenderson** [AceCentre/Echo#52]
In the 'current word' section spaces are inserted between the letter so that the word is spelled out rather than pronounced.

However, this results in some single letters being read incorrectly, primarily 'a' is read as 'uh' sometimes.

The fix might be to give each letter to the TTS system on its own, i suspect the pronunciation issue is due to the TTS using context of each letter on its own.

There also might be a way to mark it up with some kind of SSML to force correct pronunciation

**Comment by willwade** [comment]
`<say-as interpret-as="characters">SSML</say-as>`

that may be the SSML you are looking for :)
